#!/usr/bin/env bash

cd

if [ -d "$(xcode-select -p)" ]; then
  echo "Skipping Xcode Command Line Tools"
else
  echo "Installing Xcode Command Line Tools"
  xcode-select --install
  sudo xcodebuild -license accept
fi

echo "Installing thoughtbot's 'Laptop'"
curl --remote-name https://raw.githubusercontent.com/thoughtbot/laptop/master/mac | sh

if [ -d "$HOME/.oh-my-zsh" ]; then
  echo "Skipping 'Oh-My-Zsh!'"
else
  echo "Installing 'Oh-My-Zsh!'"
  curl -s curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
fi

if [ -d "$HOME/.vim/janus" ]; then
  echo "Skipping 'Janus'"
else
  echo "Installing 'Janus'"
  curl -L https://bit.ly/janus-bootstrap | bash
fi

if [ -d "$HOME/.dotfiles" ]; then
  echo "Skipping dotfiles"
else
  echo "Cloning dotfiles"
  git clone git@github.com:rachelober/dotfiles.git
fi

echo "Linking dotfiles"
rcup -v

if [ -f "$HOME/.ssh/id_rsa" ]; then
  echo "Skipping SSH key generation"
else
  echo "Creating SSH key"
  ssh-keygen -t rsa

  echo "Copied public SSH key to clipboard"
  pbcopy < ~/.ssh/id_rsa.pub

  echo "Opening GitHub, please add SSH key to account"
  open "https://github.com/settings/keys"

  echo "Starting ssh-agent and adding SSH key"
  ssh-add
fi

if [ "$(brew ls --versions macvim)" ]; then
  echo "Skipping MacVim"
else
  echo "Installing MacVim"
  brew install macvim
fi

if [ "$(brew ls --versions shellcheck)" ]; then
  echo "Skipping shellcheck"
else
  echo "Installing shellcheck"
  brew install shellcheck
fi

if [ "$(brew ls --versions ack)" ]; then
  echo "Skipping ack"
else
  echo "Installing ack"
  brew install ack
fi

if [ "$(brew ls --versions ctags)" ]; then
  echo "Skipping ctags"
else
  echo "Installing ctags"
  brew install ctags
fi

brew tap caskroom/cask
brew cask install google-chrome
brew cask install pgadmin4
# TODO: Add specific Mac App installation instructions
