#!/bin/sh

#BLACK='\033[0;30m'
RED='\033[0;31m'
#GREEN='\033[0;32m'
#ORANGE='\033[0;33m'
#BLUE='\033[0;34m'
#PURPLE='\033[0;35m'
#CYAN='\033[0;36m'
#LGTGRAY='\033[0;37m'
#DARKGRAY='\033[1;30m'
#LGTRED='\033[1;31m'
LGTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
#LGTBLUE='\033[1;34m'
#LGTPURPLE='\033[1;35m'
#LGTCYAN='\033[1;36m'
#White='\033[1;37m'
NC='\033[0m' # No Color

pretty_print() {
  printf "\\n\\n"
  printf "==========================="
  printf "\\n%s\\n" "$@"
  printf "==========================="
  printf "\\n"
}

warning_print() {
  printf "\\n%bWarning:%b %s\\n" "$YELLOW" "$NC" "$1"
}

error_print() {
  printf "\\n%bError:%b %s\\n" "$RED" "$NC" "$1"
}

success_print() {
  printf "\\n%bSuccess:%b %s\\n" "$LGTGREEN" "$NC" "$1"
}
