#!/bin/sh

DIR="${BASH_SOURCE%/*}"
if [ ! -d "$DIR" ]; then DIR="$PWD"; fi
. "$(DIR)/pretty_print"

cd || exit

pretty_print "Update dotfiles"
cd ~/.dotfiles || exit
git pull origin master

pretty_print "Link dotfiles"
rcup -v
