#!/bin/sh

# shellcheck disable=SC1091
. "pretty_print"

cd . || exit

pretty_print "Updating laptop-settings"
cd ~/.laptop-settings || exit
git pull --rebase origin master

pretty_print "Updating dotfiles"
cd ~/.dotfiles || exit
git pull --rebase origin master

pretty_print "Re-Linking dotfiles"
rcup -v
