#!/bin/sh

# shellcheck disable=SC1091
. "pretty_print"

cd "$HOME" || exit

pretty_print "Checking for Software Updates"
sudo softwareupdate -i -a

pretty_print "Run brew doctor"
brew doctor

pretty_print "Update brew"
brew update

pretty_print "Upgrade MacVim"
brew upgrade macvim

pretty_print "Upgrade ruby-build"
brew upgrade ruby-build

pretty_print "Run brew cleanup"
brew cleanup

pretty_print "Update 'Oh-My-Zsh!'"
cd ~/.oh-my-zsh || exit
git pull origin master

pretty_print "Update 'Janus'"
cd ~/.vim || exit
rake
