#!/bin/sh

# shellcheck disable=SC1091
. "pretty_print"

cd "$HOME" || exit

pretty_print "Checking for Software Updates"
sudo softwareupdate -i -a

pretty_print "Running brew doctor"
brew doctor

pretty_print "Updating brew"
brew update

pretty_print "Updating git"
brew upgrade git

pretty_print "Upgrading vim"
brew upgrade vim

pretty_print "Upgrading MacVim"
brew upgrade macvim

pretty_print "Upgrading ruby-build"
brew upgrade ruby-build

pretty_print "Upgrading ruby"
brew upgrade ruby

pretty_print "Upgrading yarn"
brew upgrade yarn

pretty_print "Upgrading node"
brew upgrade node

pretty_print "Running brew cleanup"
brew cleanup

pretty_print "Updating 'Oh-My-Zsh!'"
cd ~/.oh-my-zsh || exit
git pull origin master
